services:
  document_rag_frontend:
      build:
        context: ./frontend
        dockerfile: Dockerfile
      image: document_rag_frontend:latest
      container_name: document_rag_frontend
      ports:
        - "3000:3000"
      volumes:
        - ./frontend:/app
      networks:
        - document_rag
      depends_on:
        - document_rag_backend
      env_file:
        - frontend/.env
      
  document_rag_backend:
      build:
        context: ./backend
        dockerfile: Dockerfile
      image: document_rag_api:latest
      container_name: document_rag_backend
      ports:
        - "8000:8000"
      volumes:
        - ./backend:/app
        - ./backend/db:/app/data
      networks:
        - document_rag
      env_file:
        - backend/.env

  grafana:
    image: grafana/grafana:latest
    container_name: document_rag_grafana
    ports:
      - "3001:3000"  # Changed to 3001 since 3000 is used by frontend
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - document_rag
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=your_secure_password
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus:latest
    container_name: document_rag_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    networks:
      - document_rag
  
networks:
  document_rag:
    driver: bridge

volumes:
  grafana-storage:
  prometheus-data:
